name: Check for unmerged release PR

on:
  pull_request:

permissions:
  pull-requests: read

jobs:
  check_merge:
    uses: govuk-pay/pay-ci/.github/workflows/_prevent-merge-if-automated-release-open.yml@8597f9957716cb928c22ed66ee0704a24798ce6e
    secrets: inherit # pragma: allowlist secret
